Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/AbcSize:
  Exclude:
    - "**/*_spec.rb"

Metrics/MethodLength:
  Exclude:
    - "**/*_spec.rb"

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - "**/*_spec.rb"

Style/SymbolArray:
  Exclude:
      - "Gemfile"

AllCops:
  DisplayCopNames: true
  Exclude:
        - "db/**"
        - "db/*/*"
